urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'blog.views.home', name='home'),
    # url(r'^blog/', include('blog.foo.urls')),
	(r'^login$','blog.auth.views.login_user'),
#	(r'^$','blog.views.index'),
	(r'^home$','posting.views.index'),
	(r'^addPayment$','moneytracker.views.addPayment'),
	(r'^expenseReport$','moneytracker.views.expenseReport'),
	(r'&add_expense/(\d+)/$','moneytracker.views.add_expense'),
	(r'&add_comment/(\d+)/$','posting.views.add_comment'),
	(r'&delete_comment/(\d+)/$','posting.views.delete_comment'),
	(r'^add_location','posting.views.add_location'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$','posting.views.index',name='blog_index'),
    url(r'^login/$','auth.views.login_user'),
    url(r'^media_files/uploads/(?P<path>.*)$', 'django.views.static.serve',
        #{'document_root': 'media_files/'}),
        {'document_root': settings.MEDIA_ROOT+'/uploads/'}),
#        {'document_root': '/srv/www/blog/media_files/uploads/'}),
)
urlpatterns += staticfiles_urlpatterns()

moneytracker/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe
from django.contrib import admin
import datetime
import operator


class Category(models.Model):
	title= models.CharField(max_length=32)
	def __unicode__(self):
		return u'%s' % ( self.title)	
	class Meta:
		ordering= ['title']

class PayMethod(models.Model):
	title= models.CharField(max_length=32)
	def __unicode__(self):
		return u'%s' % ( self.title)	
	class Meta:
		ordering= ['title']
"""
class Expense_Month(models.Model):
	month = models.ForeignKey('Month')
	expense = models.ForeignKey('Expense')
"""	

class Month(models.Model):
	#title = models.CharField(max_length=32)
	year = models.IntegerField(null=False)
	month = models.IntegerField(null=False)
	available = models.DecimalField(max_digits=9,decimal_places=2,null=False)
	def save(self,*args,**kwargs):
		super(Month,self).save(*args,**kwargs)
		recurring=Expense.objects.filter(recurring=True)
		for e in recurring:
			e.month.add(self)
			e.save()
		
	def total(self):
		total = 0
		for e in self.expense_set.all():
			total += e.amount
		return total
	def __unicode__(self):
		return u'%s' % ( str(self.month)+"/"+str(self.year))	

class Expense(models.Model):
	def get_most_category():
		catList=Expense.objects.values_list('has_category',flat=True)
		categories={}
		for i in catList:
			if i in categories:
				categories[i]+=1
			else:
				categories[i]=1
		return Category.objects.get(pk=max(categories.iteritems(), key=operator.itemgetter(1))[0])	
	def get_last_month():
		month= Month.objects.order_by('-id')[:1]
		if not month:
			return null
		else:
			return month
	title = models.CharField(max_length=32)
	date = models.DateField(default=datetime.datetime.now)
	has_category = models.ForeignKey('Category', default=get_most_category)
	has_payMethod = models.ForeignKey('PayMethod')	
	note = models.TextField(blank=True,null=True)
	recurring = models.BooleanField(default=False)
	amount = models.DecimalField(max_digits=9,decimal_places=2,null=False)
	month=models.ManyToManyField('Month',default=get_last_month)
	def __unicode__(self):
		return u'%s' % ( self.title)	
	class Meta:
		ordering= ['date']

posting/models.py
from django.db import models
from thumbs import ImageWithThumbsField
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe
from django.contrib import admin

class Blog(models.Model):
	title = models.CharField(max_length=32)
	date = models.DateTimeField(auto_now_add=True)
	text = models.TextField()
	isPrivate= models.BooleanField(default=False)
	def displayText(self):
		return mark_safe(self.text)
	def __unicode__(self):
		return u'%s' % ( self.title)	
class Comment(models.Model):
	text = models.TextField(null=False)
	date = models.DateTimeField(auto_now_add=True)
	user = models.CharField(max_length=20)
	belongs_to_blog = models.ForeignKey('Blog')

class Image(models.Model):
	image_thumb = ImageWithThumbsField(upload_to='uploads',sizes=((150,150),))
	belongs_to_blog = models.ForeignKey('Blog')
	title = models.CharField(max_length=32)
	def __unicode__(self):
		return u'%s' % ( self.title)	

class Location(models.Model):
	title = models.CharField(max_length=20)
	latitude = models.DecimalField(max_digits=11,decimal_places=6,null=False)
	longitude = models.DecimalField(max_digits=11,decimal_places=6,null=False)
	date = models.DateTimeField(auto_now_add=True)
	note = models.TextField(null=True) 

templates/addPayment.html
	{% extends "base.html" %}
	{% block content %}
		<div class="row">
				<div class="span3">
					{{ month }} || ${{ month.total }} / ${{ month.available }} || {{ percentageUsed }}% Used
				</div>
			{% for expense in topExpenses %}
				<div class="span3">
					{{ expense.title }}: ${{ expense.amount }} - {{ expense.date }}	
				</div>
			{% endfor %}
		</div>
                <div class="row">
			<div class="span12 blogPost">
				<form action="" method="POST">{% csrf_token %}
					{% for field in form %}
						{{ field.label_tag }}: {{ field }}
					{% endfor %}
						
					<div id="submit"><input type="submit" value="Submit Comment"></div>
				</form>
			</div>
		</div>

    </div> <!-- /container -->
    <script type="text/javascript">
	$(document).ready(function (){
		$('#id_date').datepicker();
		//jquery wont let me do this, need to set the field to a number
		var number = document.getElementById('id_amount');
		number.type='number';
		
		var catMap={{ catMap }};
		$('#id_has_payMethod').val(catMap[$('#id_has_category').val()]);	
		$('#id_has_category').change(function(){
			$('#id_has_payMethod').val(catMap[$('#id_has_category').val()]);	
		});
	});
    </script>
        {% endblock %}

templates/auth.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Log in</title>
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<style>
body{
	font-family:Arial,Helvetica,sans-serif;
	font-size: 12px;
}
</style>
</head>
<body>
	{{ state }}
	<form action="/login/" method="post">
		{% csrf_token %}
		{% if next %}
		<input type="hidden" name="next" value="{{ next }}" />
		{% endif %}
		username:
		<input type="text" name="username" value="{{ username}}" /><br />
		password:
		<input type="password" name="password" value="" /><br />

		<input type="submit" value="Log In" />
	</form>
</body>
</html>

templates/expenseReport.html
	{% extends "base.html" %}
	{% load expense_extras %}
		{% block content %}
			<ul class="nav nav-tabs">
			{% for category,valArray in separate_expenses.items %}
				{% if forloop.counter == 1 %}
					<li class="active">
				{% else %}
					<li>
				{% endif %}
					<a href="#{{ category|repspaces }}" data-toggle="tab">{{ category }}</a>
				</li>
			{% endfor %}
				<li>
					<form action method="POST" name="changeMonth" id="changeMonth">
						{% csrf_token %}
						<select id="months" name="months" onchange="$('#changeMonth').submit();" class="reportSelect">
							{% for currmonth in months %}
								{% ifequal currmonth.id selectedmonth.id %}
									<option value="{{ currmonth.id }}" selected>{{ currmonth }}</option>
								{% endifequal %}
								{% ifnotequal currmonth.id selectedmonth.id %}
									<option value="{{ currmonth.id }}">{{ currmonth }}</option>
								{% endifnotequal %}
							{%endfor%}
						</select>
					</form>
				</li>
			</ul>
			<div class="tab-content">
			{% for category,valArray in separate_expenses.items %}
				{% if forloop.counter == 1 %}
				<div class="tab-pane active box" id="{{ category|repspaces }}">
				{% else %}
				<div class="tab-pane box" id="{{ category|repspaces }}">
				{% endif %}
					{% for expense in valArray %}
						{% if forloop.counter|divisibleby:"2" %}
							<div class="row-fluid rowEven"><div class="span4">{{ expense.title }}</div><div class="span4">{{ expense.amount }}</div><div class="span4">{{ expense.date }}/{{ expense.has_payMethod }}</div></div>	
						{% else %}
							<div class="row-fluid"><div class="span4">{{ expense.title }}</div><div class="span4">{{ expense.amount }}</div><div class="span4">{{ expense.date }}/{{ expense.has_payMethod }}</div></div>	
						{% endif %}
					{% endfor %}
							<hr />
							<div class="row-fluid"><div class="span4"></div><div class="span4">{{ separate_totals|key:category }}/{{ selectedmonth.total }}</div><div class="span4">{{ selectedmonth.available }}</div></div>	
				</div>
			{% endfor %}
			</div>
    </div> <!-- /container -->

    <script type="text/javascript">
	$(document).ready(function (){
function fnGetWidthHeight() {
            var viewportwidth;
            var viewportheight;
            // The more standards compliant browsers (mozilla/netscape/opera/chrome/IE7) use window.innerWidth and window.innerHeight
            if (typeof window.innerWidth != 'undefined') {
                viewportwidth = window.innerWidth;
                viewportheight = window.innerHeight;
            }
            // IE6 in standards compliant mode (i.e. with a valid doctype as the first line in the document)
            else if (typeof document.documentElement != 'undefined' && typeof document.documentElement.clientWidth != 'undefined' && document.documentElement.clientWidth != 0) {
                viewportwidth = document.documentElement.clientWidth;
                viewportheight = document.documentElement.clientHeight;
            }
            // older versions of IE
            else {
                viewportwidth = document.getElementsByTagName('body')[0].clientWidth;
                viewportheight = document.getElementsByTagName('body')[0].clientHeight;
            }
            alert('Your viewport width & height is ' + viewportwidth + 'x' + viewportheight);
        }
	});
    </script>
		{% endblock %}

templates/index.html
<html>
	<head>
		<title>Daniel Sauerbrun: Uncomfortable Since 1988 </title>
<LINK href="{{ STATIC_URL }}blog.css" rel="stylesheet" type="text/css">
	</head>
<body >
	<div class="menubar titlebar">
		Daniel Sauerbrun: Uncomfortable Since 1988
	</div>
	<div class="menubar">
		<div class="menuitem">
			Resume
		</div>
		<span class="menuseparator">
			>>
		</span>
		<div class="menuitem">
			Blog
		</div>
		<span class="menuseparator">
			>>
		</span>
		<div class="menuitem">
			About me
		</div>
		<span class="menuseparator">
			>>
		</span>
		<div class="menuitem">
			Idea Pad
		</div>
	</div>
	<div id="content" class="content">
	{% block content %}
		{% for e in entries reversed %}
		<h1>	{{ e.title }}</h1><br />
			{{ e.date }}<br />
			<div>
			{{ e.displayText }}<br />
			</div>
			{% for i in images %}
				{% if i.belongs_to_blog == e %}
					<a href="{{ i.image_field }}" ><img class="thumbnail" src="{{ i.image_field }}" /></a>
				{% endif %}
			{% endfor %}
			<div class="addComment">
				<form action="{% url blog.views.add_comment e.id %}" method="POST">{% csrf_token %}
					<div id="cform">
						name: {{ form.user }}
						<p> {{ form.text|linebreaks }} </p>
					</div>
					<div id="submit"><input type="submit" value="Submit Comment"></div>
				</form>
			</div>
			<div class="comments">
				{% for i in comments reversed %}
					{% if i.belongs_to_blog == e %}
						
						<div class="comment">
						
						<div class="commentUser">{{ i.user }}</div>
						<div class="commentDate">{{ i.date }}</div>
						<div class="commentTest">{{ i.text }}</div>
						</div>
					{% endif %}
				{% endfor %}
			</div>
			
			<hr />
		{% endfor %}

	{% endblock %}
	</div>
</body>

</html>

templates/navbar.html
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Daniel Sauerbrun: Uncomfortable Since 1988</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="/">Home</a></li>
		{% for name,link in menu.items %}
			<li><a href="{{ link }}">{{ name }}</a></li>
		{% endfor %}
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

templates/starter-template.html
{% extends "base.html" %}
{% block content %}
	<div id="locationModal" class="modal hide fade">
		<div class="modal-header">
			Create New Location
		</div>
		<div class="modal-body">
			<div class="alert alert-block alert-error fade in">
				<button type="button" class="close" data-dismiss="alert">x</button>
				<h4 class="alert-heading"> missing info</h4>
				<p>Make sure you fill in the title</p>
			</div>
			<div class="form-horizontal">
				<div clas="control-group">
					<label class="control-label" for="locationTitle">Title</label>
					<div class="controls">
						<input type="input" id="locationTitle" placeholder="example: Santa Barbara"/><button type class="btn" onclick="fillTitle($('#locationTitle'))" value="Auto-fill"> autofill</button>
					</div>
				</div>
				<div clas="control-group">
					<label class="control-label" for="locationNote">Note</label>
					<div class="controls">
						<textarea id="locationNote" placeholder="example: Santa Barbara" rows="3"></textarea>
					</div>
				</div>
			</div>
		</div>
		<div class="modal-footer">
			<button class="btn btn-primary" onclick="markSpot(latitude,longitude,$('#locationTitle').val(),$('#locationNote').val());" > submit</button>
			<button data-dismiss="modal" class="btn">Close</button>
		</div>
	</div>
	<div class="row">
		<div id="map" class="span9" style="height:300px">

		</div>
		<div class="span3">
			{{ location_choices.location_list }}
			<div class="btn-toolbar">
				<div class="btn-group">
					<a onclick="nextLocation()" class="btn"><i class="icon-step-backward"></i></a>
					<a href="#locationModal" role="button" class="btn" data-toggle="modal">Set new location</a>
					<a onclick="prevLocation()" class="btn"><i class="icon-step-forward"></i></a>
				</div>
			</div>

		</div>
	</div>
	<h1>Stupid musings that no one cares about</h1>
	<p>Seriously, if you're reading this you need a hobby.</p>
	{% for e in entries %}
	<div class="row">
		<div class="span12 blogPost">
				<h1>    {{ e.title }}</h1><br />
				{{ e.date }}<br />
				<div class="row">
					<div class="span12">
						<blockquote>{{ e.displayText }}</blockquote><br />
					</div>
				</div>
				<div class="row">
					<div class="offset2 span8">
						<div class="row">
						{% for i in images %}
							{% if i.belongs_to_blog == e %}
								<div class="span2">
									<a href="{{ i.image_thumb.url }}" ><img class="thumbnail" src="{{ i.image_thumb.url_150x150 }}" /></a>
								</div>
							{% endif %}
						{% endfor %}
						</div>
					</div>
				</div>
				<div class="row">
					<div class="offset1 span8">
						<div class="addComment">
							<form action="{% url posting.views.add_comment e.id %}" method="POST">{% csrf_token %}
								<div id="cform">
									name:<br /> {{ form.user }}
									<p class="input-xlarge"> {{ form.text }}{{ form.text.errors }} </p>
								</div>
								<div id="submit"><input type="submit" value="Submit Comment"></div>
							</form>
						</div>
					</div>
				</div>
				<div class="comments">
				{% for i in comments reversed %}
					{% if i.belongs_to_blog == e %}
						<div class="row">
							<div class="offset1 span8 commentPost">
								<div class="comment">
									<div class="commentUser">{{ i.user }}</div>
									{% if user.is_staff %}
										<form action="{% url posting.views.delete_comment i.id %}" method="POST">{% csrf_token %}
											<input type="submit" value="delete" style="float:right" />
										</form>
									{% endif %}
									<div class="commentDate">{{ i.date }}</div>
									<div class="commentText"><blockquote>{{ i.text }}</blockquote></div>
								</div>
							</div>
						</div>
					{% endif %}
				{% endfor %}
				</div>
		</div>
	</div>
	{% endfor %}

</div> <!-- /container -->

<script type="text/javascript"
      src="http://maps.googleapis.com/maps/api/js?key=AIzaSyAicaxhV5yGvMKxT06tgOlKDgrWUhzjjGE&sensor=false">
    </script>
<script type="text/javascript">
	$(document).ready(function(){
		$('#id_location_list').change(function(){
			changeLocation($(this).val());
		});
	
	});
</script>
<script type="text/javascript">
	// For CSRF token on POST requests
	$.ajaxSetup({ 
	     beforeSend: function(xhr, settings) {
		 function getCookie(name) {
		     var cookieValue = null;
		     if (document.cookie && document.cookie != '') {
			 var cookies = document.cookie.split(';');
			 for (var i = 0; i < cookies.length; i++) {
			     var cookie = jQuery.trim(cookies[i]);
			     // Does this cookie string begin with the name we want?
			 if (cookie.substring(0, name.length + 1) == (name + '=')) {
			     cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
			     break;
			 }
		     }
		 }
		 return cookieValue;
		 }
		 if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
		     // Only send the token to relative URLs i.e. locally.
		     xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
		 }
	     } 
	});



	var latitude=0;
	var longitude=0;
	var map;
	var markerList= new Array();
	console.log("{{location_array|escapejs}}");
	var location_array= $.parseJSON("{{ location_array|escapejs }}");
	function addMarker(markerInfoArray,key){
		var LatLng=new google.maps.LatLng(markerInfoArray[0],markerInfoArray[1]);
		var marker= new google.maps.Marker({
			position:LatLng,
			map: map,
			title:markerInfoArray[3]
		});
		var infowindow= new google.maps.InfoWindow({
			content: '<div ><b>'+markerInfoArray[3]+'</b>--'+markerInfoArray[4]+'<br />'+markerInfoArray[2]+'</div>'
		});
		google.maps.event.addListener(marker,'click',function(){
			infowindow.open(map,marker);
		});
		markerList[key]=marker;

	}
	function setMarkers(locationMap){
		jQuery.each(locationMap, function(key,value){
			addMarker(this,key);
		});
	}
	function mapError(position){

	}
	function showMap(position){
		latitude=position.coords.latitude;
		longitude=position.coords.longitude;
		var LatLngIt=new google.maps.LatLng(position.coords.latitude,position.coords.longitude);
		var mapOptions={ center : LatLngIt,zoom: 16, mapTypeId: google.maps.MapTypeId.ROADMAP};
		console.log(LatLngIt);
		map = new google.maps.Map(document.getElementById("map"),mapOptions);
		
		setMarkers(location_array);
	}
	navigator.geolocation.getCurrentPosition(showMap,mapError,{maximumAge: 50000});
	//goes back in time
	function prevLocation(){
		if($('option:selected', '#id_location_list').next('option').length!=0){
			$('option:selected', '#id_location_list').removeAttr('selected').next('option').attr('selected', 'selected');
			changeLocation($('#id_location_list').val());
		}
	}
	//goes forward in time
	function nextLocation(){
		if($('option:selected', '#id_location_list').prev('option').length!=0){
			$('option:selected', '#id_location_list').removeAttr('selected').prev('option').attr('selected', 'selected');
			changeLocation($('#id_location_list').val());
		}
	}
	function changeLocation(locationId){
		map.setCenter(markerList[locationId].getPosition());
	}


	var geocoder=new google.maps.Geocoder();
	function fillTitle(inputObject){
		var latlng=new google.maps.LatLng(latitude,longitude);
		geocoder.geocode({'latLng':latlng},function(results,status){
			if(status == google.maps.GeocoderStatus.OK){
				if(results[0]){
					for(var i=0; i< results[0].address_components.length;i++){
						var currentAddress=results[0].address_components[i];
						for(var j=0;j<currentAddress.types.length;j++){
							var currentType=currentAddress.types[j];
							if(currentType=='locality'){
								inputObject.val(currentAddress.long_name);
							}
						}
					}
				}
			}
			else{
				alert("Geocoder Failed due to: "+ status);
			}
		});
	}
	function markSpot(latitude,longitude,title,note){
		if(latitude=='' || longitude=='' || title==''){
			alert('make sure you have a title');
		}
		else{
			$.post("{% url posting.views.add_location %}",{latitude:latitude,longitude:longitude,title:title,note:note},function(data){
				var retData= $.parseJSON(data);
				//add spot to the select and add the marker to the marker array
				var markerTemp=[latitude,longitude,note,title,data[1]];
				addMarker(markerTemp,data[0]);
				$('#id_location_list').prepend('<option value="'+data[0]+'">'+title+'</option');
				console.log(markerTemp);
				
			});
		}
	}
		

</script>
{% endblock %}